services:
  db:
    image: mysql:8.0
    container_name: kosans_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - kosans_db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  volumes:
    db_data: